version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: pedropedro
      POSTGRES_DB: banco-quarkus-social
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: